# Generated by Django 6.0 on 2026-02-03 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai_nome', models.CharField(blank=True, max_length=255, verbose_name='nome do pai')),
                ('pai_cpf', models.CharField(blank=True, max_length=32, verbose_name='cpf do pai')),
                ('pai_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do pai')),
                ('pai_telefone', models.CharField(blank=True, max_length=32, verbose_name='telefone do pai')),
                ('pai_celular', models.CharField(blank=True, max_length=32, verbose_name='celular do pai')),
                ('mae_nome', models.CharField(blank=True, max_length=255, verbose_name='nome da mãe')),
                ('mae_cpf', models.CharField(blank=True, max_length=32, verbose_name='cpf da mãe')),
                ('mae_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail da mãe')),
                ('mae_telefone', models.CharField(blank=True, max_length=32, verbose_name='telefone da mãe')),
                ('mae_celular', models.CharField(blank=True, max_length=32, verbose_name='celular da mãe')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, verbose_name='nome do responsável')),
                ('responsavel_parentesco', models.CharField(blank=True, max_length=64, verbose_name='parentesco')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=32, verbose_name='cpf do responsável')),
                ('responsavel_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do responsável')),
                ('responsavel_telefone', models.CharField(blank=True, max_length=32, verbose_name='telefone do responsável')),
                ('responsavel_celular', models.CharField(blank=True, max_length=32, verbose_name='celular do responsável')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=128, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=128, verbose_name='cidade')),
                ('cep', models.CharField(blank=True, max_length=16, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, max_length=32, verbose_name='estado')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/responsavel', verbose_name='assinatura do responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aventureiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome completo')),
                ('sexo', models.CharField(blank=True, max_length=32, verbose_name='sexo')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('serie', models.CharField(blank=True, max_length=128, verbose_name='série')),
                ('colegio', models.CharField(blank=True, max_length=255, verbose_name='colégio')),
                ('bolsa', models.CharField(blank=True, max_length=16, verbose_name='bolsa')),
                ('religiao', models.CharField(blank=True, max_length=128, verbose_name='religião')),
                ('certidao', models.CharField(blank=True, max_length=255, verbose_name='certidão de nascimento')),
                ('rg', models.CharField(blank=True, max_length=64, verbose_name='RG')),
                ('orgao', models.CharField(blank=True, max_length=64, verbose_name='órgão expedidor')),
                ('cpf', models.CharField(blank=True, max_length=32, verbose_name='CPF')),
                ('camiseta', models.CharField(blank=True, max_length=32, verbose_name='camiseta')),
                ('plano', models.CharField(blank=True, max_length=16, verbose_name='possui plano de saúde')),
                ('plano_nome', models.CharField(blank=True, max_length=255, verbose_name='nome do plano')),
                ('cns', models.CharField(blank=True, max_length=64, verbose_name='CNS')),
                ('doencas', models.JSONField(blank=True, default=list, verbose_name='doenças')),
                ('condicoes', models.JSONField(blank=True, default=dict, verbose_name='condições')),
                ('alergias', models.JSONField(blank=True, default=dict, verbose_name='alergias')),
                ('deficiencias', models.JSONField(blank=True, default=list, verbose_name='deficiências')),
                ('tipo_sangue', models.CharField(blank=True, max_length=8, verbose_name='tipo sanguíneo')),
                ('declaracao_medica', models.BooleanField(default=False, verbose_name='declaracao médica aceita')),
                ('autorizacao_imagem', models.BooleanField(default=False, verbose_name='autorização de imagem')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='signatures/aventura', verbose_name='assinatura do aventureiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aventures', to='accounts.responsavel')),
            ],
        ),
    ]
