# Generated by Django 6.0 on 2026-02-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventureiro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/aventura', verbose_name='foto 3x4'),
        ),
    ]
