# Generated by Django 5.2.8 on 2026-02-04 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aventureiro_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('igreja', models.CharField(max_length=255, verbose_name='igreja')),
                ('endereco', models.CharField(max_length=255, verbose_name='endereço')),
                ('distrito', models.CharField(max_length=128, verbose_name='distrito')),
                ('numero', models.CharField(max_length=32, verbose_name='número')),
                ('bairro', models.CharField(max_length=128, verbose_name='bairro')),
                ('cep', models.CharField(max_length=16, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=128, verbose_name='cidade')),
                ('estado', models.CharField(max_length=64, verbose_name='estado')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('whatsapp', models.CharField(max_length=32, verbose_name='whatsapp')),
                ('telefone_residencial', models.CharField(blank=True, max_length=32, verbose_name='telefone residencial')),
                ('telefone_comercial', models.CharField(blank=True, max_length=32, verbose_name='telefone comercial')),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('estado_civil', models.CharField(max_length=64, verbose_name='estado civil')),
                ('cpf', models.CharField(max_length=32, verbose_name='CPF')),
                ('rg', models.CharField(max_length=32, verbose_name='RG')),
                ('conjuge', models.CharField(blank=True, max_length=255, verbose_name='esposa(o)')),
                ('filho_1', models.CharField(blank=True, max_length=255, verbose_name='filho(a) 1')),
                ('filho_2', models.CharField(blank=True, max_length=255, verbose_name='filho(a) 2')),
                ('filho_3', models.CharField(blank=True, max_length=255, verbose_name='filho(a) 3')),
                ('possui_limitacao_saude', models.CharField(max_length=8, verbose_name='possui limitação de saúde')),
                ('limitacao_saude_descricao', models.TextField(blank=True, verbose_name='descrição da limitação')),
                ('escolaridade', models.CharField(max_length=32, verbose_name='escolaridade')),
                ('autorizacao_imagem', models.BooleanField(default=False, verbose_name='autorização de imagem aceita')),
                ('declaracao_medica', models.BooleanField(default=False, verbose_name='declaração médica aceita')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/diretoria', verbose_name='foto 3x4')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='signatures/diretoria', verbose_name='assinatura da diretoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diretoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
