# Generated by Django 5.2.8 on 2026-02-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='profiles',
            field=models.JSONField(blank=True, default=list, verbose_name='perfis de acesso'),
        ),
    ]
