# Generated by Django 5.2.8 on 2026-02-05 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccess_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='numero whatsapp')),
                ('notify_cadastro', models.BooleanField(default=True, verbose_name='notificacao de cadastro')),
                ('notify_financeiro', models.BooleanField(default=False, verbose_name='notificacao financeira')),
                ('notify_geral', models.BooleanField(default=False, verbose_name='notificacao geral')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, verbose_name='numero destino')),
                ('notification_type', models.CharField(choices=[('cadastro', 'Cadastro'), ('financeiro', 'Financeiro'), ('geral', 'Geral')], default='geral', max_length=32, verbose_name='tipo notificacao')),
                ('message_text', models.TextField(verbose_name='mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='status envio')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='tentativas')),
                ('provider_message_id', models.CharField(blank=True, max_length=128, verbose_name='id provedor')),
                ('last_error', models.TextField(blank=True, verbose_name='ultimo erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
