# Generated by Django 5.2.8 on 2026-02-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_whatsapppreference_whatsappqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapppreference',
            name='cadastro_message',
            field=models.TextField(blank=True, verbose_name='mensagem de cadastro'),
        ),
    ]
