# Generated by Django 5.2.8 on 2026-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_whatsapppreference_cadastro_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('cadastro', 'Cadastro'), ('teste', 'Teste')], max_length=32, unique=True, verbose_name='tipo de notificacao')),
                ('message_text', models.TextField(verbose_name='mensagem')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
