# Generated by Django 5.2.8 on 2026-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_whatsapptemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappqueue',
            name='notification_type',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('financeiro', 'Financeiro'), ('geral', 'Geral'), ('teste', 'Teste')], default='geral', max_length=32, verbose_name='tipo notificacao'),
        ),
    ]
