# Generated by Django 5.2.8 on 2026-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_whatsappqueue_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapppreference',
            name='notify_cadastro',
            field=models.BooleanField(default=False, verbose_name='notificacao de cadastro'),
        ),
    ]
