# Generated by Django 5.2.8 on 2026-02-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_whatsapppreference_notify_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('template_type', models.CharField(choices=[('responsavel', 'Responsável'), ('aventureiro', 'Aventureiro'), ('diretoria', 'Diretoria')], max_length=24, verbose_name='tipo')),
                ('background', models.ImageField(upload_to='documentos/templates', verbose_name='imagem de fundo')),
                ('positions', models.JSONField(blank=True, default=list, verbose_name='posições')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'template de documento',
                'verbose_name_plural': 'templates de documentos',
            },
        ),
    ]
