# Generated by Django 5.2.8 on 2026-02-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_documentotemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AventureiroFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_data', models.JSONField(blank=True, default=dict, verbose_name='dados da ficha de inscricao')),
                ('ficha_medica_data', models.JSONField(blank=True, default=dict, verbose_name='dados da ficha medica')),
                ('declaracao_medica_data', models.JSONField(blank=True, default=dict, verbose_name='dados da declaracao medica')),
                ('termo_imagem_data', models.JSONField(blank=True, default=dict, verbose_name='dados do termo de imagem')),
                ('assinatura_inscricao', models.ImageField(blank=True, null=True, upload_to='signatures/fichas/inscricao', verbose_name='assinatura da ficha de inscricao')),
                ('assinatura_declaracao_medica', models.ImageField(blank=True, null=True, upload_to='signatures/fichas/declaracao_medica', verbose_name='assinatura da declaracao medica')),
                ('assinatura_termo_imagem', models.ImageField(blank=True, null=True, upload_to='signatures/fichas/termo_imagem', verbose_name='assinatura do termo de imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aventureiro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_completa', to='accounts.aventureiro')),
            ],
            options={
                'verbose_name': 'ficha completa do aventureiro',
                'verbose_name_plural': 'fichas completas dos aventureiros',
            },
        ),
    ]
