# Generated by Django 5.2.8 on 2026-02-07 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_aventureiroficha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInscricaoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ficha_inscricao', 'Ficha de inscrição'), ('ficha_medica', 'Ficha médica'), ('declaracao_medica', 'Declaração médica'), ('termo_imagem', 'Termo de imagem')], max_length=32, verbose_name='tipo de documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aventureiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='accounts.aventureiro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_inscricao_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento de inscrição gerado',
                'verbose_name_plural': 'documentos de inscrição gerados',
                'ordering': ('-created_at',),
            },
        ),
    ]
