# Generated by Django 5.2.8 on 2026-02-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_documentoinscricaogerado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretoriaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromisso_data', models.JSONField(blank=True, default=dict, verbose_name='dados do compromisso voluntariado')),
                ('termo_imagem_data', models.JSONField(blank=True, default=dict, verbose_name='dados do termo de imagem')),
                ('assinatura_compromisso', models.ImageField(blank=True, null=True, upload_to='signatures/fichas/diretoria_compromisso', verbose_name='assinatura do compromisso voluntariado')),
                ('assinatura_termo_imagem', models.ImageField(blank=True, null=True, upload_to='signatures/fichas/diretoria_termo_imagem', verbose_name='assinatura do termo de imagem da diretoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diretoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_completa', to='accounts.diretoria')),
            ],
            options={
                'verbose_name': 'ficha completa da diretoria',
                'verbose_name_plural': 'fichas completas da diretoria',
            },
        ),
    ]
