# Generated by Django 5.2.8 on 2026-02-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_diretoriaficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapppreference',
            name='notify_diretoria',
            field=models.BooleanField(default=False, verbose_name='notificacao de cadastro de diretoria'),
        ),
        migrations.AlterField(
            model_name='whatsappqueue',
            name='notification_type',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('diretoria', 'Diretoria'), ('financeiro', 'Financeiro'), ('geral', 'Geral'), ('teste', 'Teste')], default='geral', max_length=32, verbose_name='tipo notificacao'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='notification_type',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('diretoria', 'Diretoria'), ('teste', 'Teste')], max_length=32, unique=True, verbose_name='tipo de notificacao'),
        ),
    ]
