# Generated by Django 5.2.8 on 2026-02-08 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_whatsapppreference_notify_diretoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='menu_allow',
            field=models.JSONField(blank=True, default=list, verbose_name='menus liberados por usuário'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='menu_deny',
            field=models.JSONField(blank=True, default=list, verbose_name='menus bloqueados por usuário'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.CharField(choices=[('responsavel', 'Responsável'), ('diretoria', 'Diretoria'), ('diretor', 'Diretor'), ('professor', 'Professor')], default='responsavel', max_length=32, verbose_name='perfil de acesso'),
        ),
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nome')),
                ('menu_permissions', models.JSONField(blank=True, default=list, verbose_name='menus permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='access_groups', to=settings.AUTH_USER_MODEL, verbose_name='usuários')),
            ],
            options={
                'verbose_name': 'grupo de acesso',
                'verbose_name_plural': 'grupos de acesso',
                'ordering': ('name',),
            },
        ),
    ]
