# Generated by Django 5.2.8 on 2026-02-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='data do evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora do evento'),
        ),
    ]
