# Generated by Django 5.2.8 on 2026-02-08 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_evento_event_date_evento_event_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=160, verbose_name='nome da pré-configuração')),
                ('event_name', models.CharField(blank=True, max_length=255, verbose_name='nome padrão do evento')),
                ('event_type', models.CharField(blank=True, max_length=128, verbose_name='tipo padrão do evento')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='data padrão')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='hora padrão')),
                ('fields_data', models.JSONField(blank=True, default=list, verbose_name='campos padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_presets_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pré-configuração de evento',
                'verbose_name_plural': 'pré-configurações de evento',
                'ordering': ('preset_name',),
            },
        ),
    ]
