# Generated by Django 5.2.8 on 2026-02-08 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_eventopreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False, verbose_name='presente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('aventureiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_evento', to='accounts.aventureiro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='accounts.evento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presença em evento',
                'verbose_name_plural': 'presenças em evento',
                'ordering': ('aventureiro__nome',),
                'unique_together': {('evento', 'aventureiro')},
            },
        ),
    ]
