# Generated by Django 5.2.12 on 2026-03-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_eventofaltainscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapppreference',
            name='notify_loja',
            field=models.BooleanField(default=False, verbose_name='notificacao de pedido loja pago'),
        ),
        migrations.AlterField(
            model_name='whatsappqueue',
            name='notification_type',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('diretoria', 'Diretoria'), ('confirmacao', 'Confirmação'), ('financeiro', 'Financeiro'), ('loja', 'Loja'), ('geral', 'Geral'), ('teste', 'Teste')], default='geral', max_length=32, verbose_name='tipo notificacao'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='notification_type',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('diretoria', 'Diretoria'), ('confirmacao', 'Confirmação'), ('financeiro', 'Financeiro'), ('loja', 'Loja'), ('teste', 'Teste')], max_length=32, unique=True, verbose_name='tipo de notificacao'),
        ),
    ]
