# Generated by Django 5.2.12 on 2026-03-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_whatsapppreference_notify_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de fim do evento'),
        ),
        migrations.AddField(
            model_name='eventopreset',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de fim padrão'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de início do evento'),
        ),
        migrations.AlterField(
            model_name='eventopreset',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de início padrão'),
        ),
    ]
