# Generated by Django 5.2.12 on 2026-03-14 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_evento_event_end_time_eventopreset_event_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lojapedido',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_loja', to='accounts.evento'),
        ),
        migrations.AddField(
            model_name='lojaproduto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_loja', to='accounts.evento'),
        ),
        migrations.CreateModel(
            name='EventoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados da inscrição')),
                ('quer_comprar_itens', models.BooleanField(default=False, verbose_name='quer comprar itens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='accounts.evento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_inscricoes', to='accounts.responsavel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscrição de evento',
                'verbose_name_plural': 'inscrições de eventos',
                'ordering': ('-created_at',),
                'unique_together': {('evento', 'user')},
            },
        ),
    ]
