# Generated by Django 5.2.12 on 2026-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_lojapedido_evento_lojaproduto_evento_eventoinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricao_publica',
            field=models.BooleanField(default=False, verbose_name='página pública de inscrição'),
        ),
    ]
