# Generated by Django 5.2.12 on 2026-03-14 02:42

from django.conf import settings
from django.db import migrations, models


def populate_eventoinscricao_codes(apps, schema_editor):
    EventoInscricao = apps.get_model('accounts', 'EventoInscricao')
    event_ids = (
        EventoInscricao.objects
        .values_list('evento_id', flat=True)
        .distinct()
    )
    for event_id in event_ids:
        used = set()
        rows = EventoInscricao.objects.filter(evento_id=event_id).order_by('id')
        for row in rows:
            current = str(getattr(row, 'codigo_inscricao', '') or '').strip()
            if current and current not in used:
                used.add(current)
                continue
            new_code = None
            for number in range(1000):
                code = f'{number:03d}'
                if code not in used:
                    new_code = code
                    break
            if new_code is None:
                raise RuntimeError(f'Evento {event_id} excedeu o limite de 1000 codigos de inscricao.')
            row.codigo_inscricao = new_code
            row.save(update_fields=['codigo_inscricao'])
            used.add(new_code)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_evento_inscricao_publica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinscricao',
            name='codigo_inscricao',
            field=models.CharField(blank=True, editable=False, max_length=3, verbose_name='codigo da inscricao'),
        ),
        migrations.RunPython(populate_eventoinscricao_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventoinscricao',
            constraint=models.UniqueConstraint(fields=('evento', 'codigo_inscricao'), name='uniq_evento_codigo_inscricao'),
        ),
    ]
