# Generated by Django 5.2.12 on 2026-03-23 19:40

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_rebuild_aventureiro_codigos_legiveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroComprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to=accounts.models.financeiro_comprovante_upload_to, verbose_name='comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_comprovantes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comprovante de gasto do clube',
                'verbose_name_plural': 'comprovantes de gastos do clube',
                'ordering': ('-created_at',),
            },
        ),
    ]
