# Generated by Django 5.2.12 on 2026-05-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_whatsappqueue_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojapedidoitem',
            name='aventureiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_loja', to='accounts.aventureiro'),
        ),
        migrations.AddField(
            model_name='lojapedidoitem',
            name='aventureiro_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='aventureiro (snapshot)'),
        ),
        migrations.AddField(
            model_name='lojaprodutovariacao',
            name='relatorio_exibir_aventureiro',
            field=models.BooleanField(default=False, verbose_name='exibir aventureiro no relatorio'),
        ),
    ]
