# Generated by Django 5.2.12 on 2026-05-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_lojapedidoitem_aventureiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeirocomprovante',
            name='destino',
            field=models.CharField(choices=[('caixa_liquido', 'Caixa liquido / mensalidades'), ('loja_geral', 'Loja geral'), ('eventos', 'Eventos')], default='caixa_liquido', max_length=32, verbose_name='abater em'),
        ),
    ]
