# Generated by Django 5.2.12 on 2026-05-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_financeirocomprovante_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventureiro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
