# Generated by Django 5.2.12 on 2026-05-18 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_aventureiro_ativo_responsavel_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinscricao',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='inscricao cancelada'),
        ),
        migrations.AddField(
            model_name='eventoinscricao',
            name='cancelada_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelada em'),
        ),
        migrations.AddField(
            model_name='eventoinscricao',
            name='cancelada_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_inscricoes_canceladas', to=settings.AUTH_USER_MODEL),
        ),
    ]
