# Generated by Django 5.2.12 on 2026-05-19 00:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_eventoinscricao_cancelada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinscricao',
            name='valor_estornado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor estornado no cancelamento'),
        ),
    ]
