# Generated by Django 5.2.12 on 2026-05-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_backfill_eventoinscricao_valor_estornado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojapedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartao')], default='pix', max_length=24, verbose_name='forma de pagamento'),
        ),
    ]
