# Generated by Django 5.2.12 on 2026-05-19 01:35

from django.db import migrations, models


def backfill_quantidade_entregue(apps, schema_editor):
    LojaPedidoItem = apps.get_model('accounts', 'LojaPedidoItem')
    itens = LojaPedidoItem.objects.filter(pedido__entregue=True)
    for item in itens.iterator():
        item.quantidade_entregue = int(item.quantidade or 0)
        item.save(update_fields=['quantidade_entregue'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_alter_lojapedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojapedidoitem',
            name='quantidade_entregue',
            field=models.PositiveIntegerField(default=0, verbose_name='quantidade entregue'),
        ),
        migrations.RunPython(backfill_quantidade_entregue, migrations.RunPython.noop),
    ]
