# Generated by Django 5.2.12 on 2026-05-21 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_lojapedidoitem_quantidade_entregue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAtendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('force_password_change', models.BooleanField(default=True, verbose_name='troca de senha obrigatoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_atendentes_criados', to=settings.AUTH_USER_MODEL)),
                ('eventos', models.ManyToManyField(blank=True, related_name='atendentes', to='accounts.evento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento_atendente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atendente de evento',
                'verbose_name_plural': 'atendentes de eventos',
                'ordering': ('user__username',),
            },
        ),
    ]
