# Generated by Django 5.2.12 on 2026-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_lojapedido_transacao_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='taxa_cartao_evento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='taxa de cartao do evento'),
        ),
    ]
