# Generated by Django 5.2.12 on 2026-06-04 19:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_evento_taxa_cartao_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_percent', models.DecimalField(decimal_places=2, default=Decimal('0.49'), max_digits=5, verbose_name='taxa Pix (%)')),
                ('debit_percent', models.DecimalField(decimal_places=2, default=Decimal('1.99'), max_digits=5, verbose_name='taxa débito (%)')),
                ('credit_1x_percent', models.DecimalField(decimal_places=2, default=Decimal('4.98'), max_digits=5, verbose_name='taxa crédito 1x (%)')),
                ('credit_2_6_percent', models.DecimalField(decimal_places=2, default=Decimal('2.99'), max_digits=5, verbose_name='taxa crédito 2x a 6x (%)')),
                ('credit_7_12_percent', models.DecimalField(decimal_places=2, default=Decimal('3.09'), max_digits=5, verbose_name='taxa crédito 7x a 12x (%)')),
                ('credit_13_18_percent', models.DecimalField(decimal_places=2, default=Decimal('3.19'), max_digits=5, verbose_name='taxa crédito 13x a 18x (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercadopago_fee_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuração de taxas Mercado Pago',
                'verbose_name_plural': 'configurações de taxas Mercado Pago',
            },
        ),
    ]
