# Generated by Django 5.2.12 on 2026-06-10 00:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_mp_fee_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_10x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.90'), max_digits=5, verbose_name='(legado) 10x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_11x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('33.99'), max_digits=5, verbose_name='(legado) 11x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_12x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('37.08'), max_digits=5, verbose_name='(legado) 12x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_13_18_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.59'), max_digits=5, verbose_name='(legado) 13-18x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_1x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.98'), max_digits=5, verbose_name='crédito à vista 1x (%)'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_2_6_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.90'), max_digits=5, verbose_name='(legado) 2-6x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_2x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.98'), max_digits=5, verbose_name='(legado) 2x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_3x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.97'), max_digits=5, verbose_name='(legado) 3x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_4x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.96'), max_digits=5, verbose_name='(legado) 4x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_5x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('14.95'), max_digits=5, verbose_name='(legado) 5x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_6x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('17.94'), max_digits=5, verbose_name='(legado) 6x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_7_12_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.55'), max_digits=5, verbose_name='(legado) 7-12x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_7x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.63'), max_digits=5, verbose_name='(legado) 7x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_8x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('24.72'), max_digits=5, verbose_name='(legado) 8x'),
        ),
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='credit_9x_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('27.81'), max_digits=5, verbose_name='(legado) 9x'),
        ),
    ]
