# Generated by Django 5.2.12 on 2026-06-10 00:15

from decimal import Decimal
from django.db import migrations, models


def sync_default_fee_values(apps, schema_editor):
    Config = apps.get_model('accounts', 'MercadoPagoFeeConfig')
    for item in Config.objects.all():
        item.pix_percent = Decimal('1.00')
        item.credit_1x_percent = Decimal('4.98')
        item.credit_per_parcel_2_6x = Decimal('2.99')
        item.credit_per_parcel_7_12x = Decimal('3.09')
        item.save(update_fields=[
            'pix_percent',
            'credit_1x_percent',
            'credit_per_parcel_2_6x',
            'credit_per_parcel_7_12x',
            'updated_at',
        ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_alter_mercadopagofeeconfig_credit_10x_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagofeeconfig',
            name='pix_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='taxa Pix (%)'),
        ),
        migrations.RunPython(sync_default_fee_values, noop_reverse),
    ]
