# Generated by Django 5.2.12 on 2026-06-14 21:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_mercadopagofeeconfig_pix_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinscricao',
            name='desconto_codigo_texto',
            field=models.CharField(blank=True, max_length=24, verbose_name='codigo de desconto usado'),
        ),
        migrations.AddField(
            model_name='eventoinscricao',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='percentual desconto'),
        ),
        migrations.AddField(
            model_name='eventoinscricao',
            name='desconto_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor desconto'),
        ),
        migrations.AddField(
            model_name='eventoinscricao',
            name='valor_inscricao_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor original da inscricao'),
        ),
        migrations.CreateModel(
            name='EventoDescontoCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='codigo de desconto')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percentual de desconto')),
                ('usado', models.BooleanField(default=False, verbose_name='usado')),
                ('usado_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_descontos_criados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desconto_codigos', to='accounts.evento')),
                ('usado_por_inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desconto_codigos_utilizados', to='accounts.eventoinscricao')),
            ],
            options={
                'verbose_name': 'codigo de desconto do evento',
                'verbose_name_plural': 'codigos de desconto dos eventos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='eventoinscricao',
            name='desconto_codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_com_desconto', to='accounts.eventodescontocodigo'),
        ),
    ]
