# Generated by Django 5.2.15 on 2026-06-19 11:53

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_eventoinscricao_desconto_codigo_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCustoComprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=accounts.models.evento_custo_comprovante_upload_to, verbose_name='comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='accounts.eventocusto')),
            ],
            options={
                'verbose_name': 'comprovante de custo de evento',
                'verbose_name_plural': 'comprovantes de custos de eventos',
                'ordering': ('id',),
            },
        ),
    ]
