# Generated by Django 5.2.12 on 2026-06-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_eventocustocomprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(db_index=True, verbose_name='data do movimento')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='id da operacao')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor bruto')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor liquido')),
                ('saldo_pos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='saldo pos movimento')),
                ('origem', models.CharField(choices=[('pix', 'Pix'), ('ted', 'TED/Transferencia'), ('taxa', 'Taxa'), ('estorno', 'Estorno'), ('transferencia', 'Transferencia interna'), ('outros', 'Outros')], default='outros', max_length=32, verbose_name='origem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conferido', 'Conferido'), ('ajustar_financeiro', 'Ajustar financeiro'), ('ignorar', 'Ignorar')], db_index=True, default='pendente', max_length=32, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observacao')),
                ('raw_text', models.TextField(blank=True, verbose_name='texto bruto do extrato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'transacao do extrato',
                'verbose_name_plural': 'transacoes do extrato',
                'ordering': ('-data_movimento', '-id'),
                'indexes': [models.Index(fields=['data_movimento', 'status'], name='accounts_ex_data_mo_f16a21_idx'), models.Index(fields=['external_id'], name='accounts_ex_externa_41d786_idx')],
            },
        ),
    ]
