from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth.views import LoginView

from .views import (
    RegisterView,
    PasswordRecoveryView,
    NovoCadastroLoginView,
    NovoCadastroInscricaoView,
    VerificarDocumentoView,
    NovoCadastroMedicaView,
    NovoCadastroDeclaracaoMedicaView,
    NovoCadastroTermoImagemView,
    NovoCadastroResumoView,
    NovoCadastroSucessoView,
    NovoCadastroDiretoriaLoginView,
    NovoCadastroDiretoriaCompromissoView,
    NovoCadastroDiretoriaTermoView,
    NovoCadastroDiretoriaResumoView,
    LogoutRedirectView,
    ResponsavelView,
    DiretoriaView,
    AventuraView,
    ConfirmacaoView,
    PainelView,
    MeusDadosView,
    MeuResponsavelDetalheView,
    MeuResponsavelAdicionarAventureiroView,
    MeuResponsavelEditarView,
    MeuAventureiroDetalheView,
    MeuAventureiroEditarView,
    MinhaDiretoriaDetalheView,
    MinhaDiretoriaEditarView,
    AventureirosGeraisView,
    AventureiroGeralDetalheView,
    EventosView,
    PresencaView,
    PresencaStatusApiView,
    PresencaToggleApiView,
    AuditoriaView,
    UsuariosView,
    PermissoesView,
    FinanceiroView,
    PontosView,
    ApostilaView,
    LojaView,
    LojaPedidoCreatePixApiView,
    LojaPedidoStatusApiView,
    LojaPedidoWebhookView,
    PagamentoMensalidadeStatusApiView,
    PagamentoMensalidadeWebhookView,
    WhatsAppView,
    UsuarioDetalheView,
    UsuarioPermissaoEditarView,
    AlterarPerfilAtivoView,
    DocumentosInscricaoView,
    DocumentoInscricaoVisualizarView,
    DocumentoGerarView,
)

app_name = 'accounts'

urlpatterns = [
    # Página inicial -> login
    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False)),
    path('register/', RegisterView.as_view(), name='register'),
    path('recuperar-senha/', PasswordRecoveryView.as_view(), name='password_recovery'),
    path('novo-cadastro/login/', NovoCadastroLoginView.as_view(), name='novo_cadastro_login'),
    path('novo-cadastro/verificar-documento/', VerificarDocumentoView.as_view(), name='novo_cadastro_verificar_documento'),
    path('novo-cadastro/inscricao/', NovoCadastroInscricaoView.as_view(), name='novo_cadastro_inscricao'),
    path('novo-cadastro/medica/', NovoCadastroMedicaView.as_view(), name='novo_cadastro_medica'),
    path('novo-cadastro/declaracao-medica/', NovoCadastroDeclaracaoMedicaView.as_view(), name='novo_cadastro_declaracao'),
    path('novo-cadastro/termo-imagem/', NovoCadastroTermoImagemView.as_view(), name='novo_cadastro_termo'),
    path('novo-cadastro/resumo/', NovoCadastroResumoView.as_view(), name='novo_cadastro_resumo'),
    path('novo-cadastro/sucesso/', NovoCadastroSucessoView.as_view(), name='novo_cadastro_sucesso'),
    path('novo-cadastro-diretoria/login/', NovoCadastroDiretoriaLoginView.as_view(), name='novo_diretoria_login'),
    path('novo-cadastro-diretoria/compromisso/', NovoCadastroDiretoriaCompromissoView.as_view(), name='novo_diretoria_compromisso'),
    path('novo-cadastro-diretoria/termo-imagem/', NovoCadastroDiretoriaTermoView.as_view(), name='novo_diretoria_termo'),
    path('novo-cadastro-diretoria/resumo/', NovoCadastroDiretoriaResumoView.as_view(), name='novo_diretoria_resumo'),
    path('legacy/responsavel/', ResponsavelView.as_view(), name='legacy_responsavel'),
    path('legacy/aventura/', AventuraView.as_view(), name='legacy_aventura'),
    path('legacy/confirmacao/', ConfirmacaoView.as_view(), name='legacy_confirmacao'),
    path('legacy/diretoria/', DiretoriaView.as_view(), name='legacy_diretoria'),
    path('responsavel/', ResponsavelView.as_view(), name='responsavel'),
    path('diretoria/', DiretoriaView.as_view(), name='diretoria'),
    path('aventura/', AventuraView.as_view(), name='aventura'),
    path('confirmacao/', ConfirmacaoView.as_view(), name='confirmacao'),
    path('painel/', PainelView.as_view(), name='painel'),
    path('meus-dados/', MeusDadosView.as_view(), name='meus_dados'),
    path('meus-dados/responsavel/', MeuResponsavelDetalheView.as_view(), name='meu_responsavel'),
    path('meus-dados/responsavel/adicionar-aventureiro/', MeuResponsavelAdicionarAventureiroView.as_view(), name='meu_responsavel_adicionar_aventureiro'),
    path('meus-dados/responsavel/editar/', MeuResponsavelEditarView.as_view(), name='editar_meu_responsavel'),
    path('meus-dados/diretoria/', MinhaDiretoriaDetalheView.as_view(), name='minha_diretoria'),
    path('meus-dados/diretoria/editar/', MinhaDiretoriaEditarView.as_view(), name='editar_minha_diretoria'),
    path('meus-dados/aventureiro/<int:pk>/', MeuAventureiroDetalheView.as_view(), name='meu_aventureiro'),
    path('meus-dados/aventureiro/<int:pk>/editar/', MeuAventureiroEditarView.as_view(), name='editar_meu_aventureiro'),
    path('eventos/', EventosView.as_view(), name='eventos'),
    path('presenca/', PresencaView.as_view(), name='presenca'),
    path('presenca/status/', PresencaStatusApiView.as_view(), name='presenca_status_api'),
    path('presenca/toggle/', PresencaToggleApiView.as_view(), name='presenca_toggle_api'),
    path('auditoria/', AuditoriaView.as_view(), name='auditoria'),
    path('usuarios/', UsuariosView.as_view(), name='usuarios'),
    path('financeiro/', FinanceiroView.as_view(), name='financeiro'),
    path('pontos/', PontosView.as_view(), name='pontos'),
    path('apostila/', ApostilaView.as_view(), name='apostila'),
    path('loja/', LojaView.as_view(), name='loja'),
    path('loja/pedidos/criar-pix/', LojaPedidoCreatePixApiView.as_view(), name='loja_pedido_criar_pix'),
    path('loja/pedidos/<int:pk>/status/', LojaPedidoStatusApiView.as_view(), name='loja_pedido_status'),
    path('loja/mp-webhook/', LojaPedidoWebhookView.as_view(), name='loja_mp_webhook'),
    path('financeiro/pagamentos/<int:pk>/status/', PagamentoMensalidadeStatusApiView.as_view(), name='financeiro_pagamento_status'),
    path('financeiro/mp-webhook/', PagamentoMensalidadeWebhookView.as_view(), name='financeiro_mp_webhook'),
    path('permissoes/', PermissoesView.as_view(), name='permissoes'),
    path('whatsapp/', WhatsAppView.as_view(), name='whatsapp'),
    path('documentos/', DocumentosInscricaoView.as_view(), name='documentos_inscricao'),
    path('documentos/inscricao-gerado/<int:pk>/', DocumentoInscricaoVisualizarView.as_view(), name='documento_inscricao_visualizar'),
    path('documentos/gerar/<int:template_id>/<str:kind>/<int:pk>/', DocumentoGerarView.as_view(), name='documento_gerar'),
    path('usuarios/<int:pk>/', UsuarioDetalheView.as_view(), name='usuario_detalhe'),
    path('usuarios/<int:pk>/editar/', UsuarioPermissaoEditarView.as_view(), name='editar_usuario_permissoes'),
    path('perfil/alternar/', AlterarPerfilAtivoView.as_view(), name='alternar_perfil'),
    path('aventureiros-gerais/', AventureirosGeraisView.as_view(), name='aventureiros_gerais'),
    path('aventureiros-gerais/<int:pk>/', AventureiroGeralDetalheView.as_view(), name='aventureiro_geral'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutRedirectView.as_view(), name='logout'),
]
